name: deploy-blog-develop

on:
  push:
    # branches:
    #   - develop
    paths:
      - blog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update submodule
      run: git submodule update --init --recursive

    # - name: Remove all files in target path
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     port: ${{ secrets.SSH_PORT }}
    #     script: |
    #       cd ${{ secrets.TARGET_PATH }}/develop/blog/containers
    #       sudo docker compose down
    #       rm -rf *

    - name: Upload artifact to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: blog/containers/*
        target: ${{ secrets.TARGET_PATH }}

    - name: Recreate Blog
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.TARGET_PATH }}/develop/blog/containers
          sudo docker compose build --no-cache
          sudo docker compose up -d